### ISSUE TITLE
Support for node-addon-api

### ISSUE THREAD

**Issue by erdii** [mafintosh/prebuildify#13]
Hey @mafintosh! First of all: Really nice work!

I'd like to use prebuildify with node-addon-api and c++, but on requiring the prebuild with node-gyp-build the process crashed with:

```
internal/modules/cjs/loader.js:718
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: Module did not self-register.
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at load (/Users/erdii/playgrounds/n-api/cpp-example/node_modules/node-gyp-build/index.js:13:10)
    at Object.<anonymous> (/Users/erdii/playgrounds/n-api/cpp-example/index.js:1:105)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
```

After investigating a bit I found out, that build/Release only contains a nothing.node when building with prebuildify, but when building with node-gyp everything is fine.

Am I missing something here?

The project is uploaded here: https://github.com/erdii/napi-cpp-example

index.js has both require-lines with the node-gyp-build one commented out.
`npm run _prebuild` runs `prebuildify --napi` and `npm run build` runs `node-gyp rebuild`.
To require the module run `node index.js` or `node  example.js`.

Thank you very much in advance!

PS: I just watched your "Mad Science" talk on YT and the part where you boot ubuntu from the mounted torrent iso is so freakin' cool! 🎉

**Comment by fraxken** [comment]
Hey,

I have the same error on my side. I use node-addon-api too (On Windows 10 - 64 bit).

Any news/feedbacks ?

Best Regards,
Thomas

**Comment by mafintosh** [comment]
Hi.

Thanks for the nice words about my talk :)

You need to load the prebuild from the prebuilds folder. You can do that easily using node-gyp-build
Check the bottom of the prebuildify README.

```js
// this will load the correct prebuild for your platform
const bindings = require('node-gyp-build')(__dirname)
```

**Comment by fraxken** [comment]
Hi @mafintosh, 

https://github.com/SlimIO/Windrive/tree/v1.4.0

Same error (node-gyp-build was already setup). But when i delete my "build" directory (after generating the prebuilds with prebuildify --napi, it doesn't work).

Maybe i'v miss something... (first time i do this).

```
> @slimio/windrive@1.3.0 test F:\Code\SlimIO\Windrive
> ava --verbose


internal/modules/cjs/loader.js:718
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: Module did not self-register.
    at Module._extensions..node (internal/modules/cjs/loader.js:718:18)
    at Object.require.extensions.(anonymous function) [as .node] (F:\Code\SlimIO\Windrive\node_modules\ava\lib\process-adapter.js:100:4)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at load (F:\Code\SlimIO\Windrive\node_modules\node-gyp-build\index.js:13:10)
    at Object.<anonymous> (F:\Code\SlimIO\Windrive\index.js:5:43)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at extensions.(anonymous function) (F:\Code\SlimIO\Windrive\node_modules\require-precompiled\index.js:16:3)
    at Object.require.extensions.(anonymous function) [as .js] (F:\Code\SlimIO\Windrive\node_modules\ava\lib\process-adapter.js:100:4)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

Thanks for your time ! 

Best Regards,
Thomas

**Comment by fraxken** [comment]
Hi,

I checked the package node-gyp-build and everything is ok on this side. load.path return the complete path to my `prebuilds/win32-x64/node-napi.node`.

So i guess there is something wrong with the prebuilds .node. I'm trying to figure out what's wrong.

Best Regards,
Thomas

**Comment by mafintosh** [comment]
@fraxken try requiring the prebuild directly to see if that makes a difference? which node are you running?

**Comment by erdii** [comment]
I am using this to load the prebuild: 
```
// this will load the correct prebuild for your platform
const bindings = require('node-gyp-build')(__dirname)
```

I think that slipped here, so I guess prebuildify doesn't find out where node-addon-api registers itself as an napi "consumer":

> After investigating a bit I found out, that build/Release only contains a nothing.node when building with prebuildify, but when building with node-gyp everything is fine.

**Comment by fraxken** [comment]
Hi,

This issue seem to be fixed by one of the latest version of node-addon-api. Since i upgraded to 1.6.1 everything work fine ! 

Best Regards,
Thomas

**Comment by ralphtheninja** [comment]
This can be closed?

**Comment by erdii** [comment]
Yep. Seems to work with the latest version of node-addon-api. 👍
